# Generated by Django 4.2.5 on 2023-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phn_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
