# Generated by Django 4.2.5 on 2023-10-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_job_type_job_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='rec',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
    ]
