# Generated by Django 4.2.5 on 2023-10-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
