# Generated by Django 4.2.5 on 2023-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_apply_applydate_remove_apply_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='jobtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
